name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          tools: composer

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install -g sass typescript

      - name: Create tsconfig.json for TypeScript compilation
        run: |
          echo '{
            "compilerOptions": {
              "target": "es5",
              "module": "commonjs",
              "outDir": "pkg/assets/js",
              "rootDir": "pkg/assets/ts",
              "strict": false,
              "esModuleInterop": true,
              "skipLibCheck": true,
              "forceConsistentCasingInFileNames": true,
              "lib": ["es6", "dom"]
            },
            "include": ["pkg/assets/ts/**/*"]
          }' > tsconfig.json
          
      - name: Compile Sass to CSS
        run: |
          mkdir -p pkg/assets/css
          sass pkg/assets/sass/main.scss:pkg/assets/css/main.css --style=compressed
          sass pkg/assets/sass/ZigWalk.scss:pkg/assets/css/ZigWalk.css --style=compressed
          sass pkg/assets/sass/znek-override.scss:pkg/assets/css/znek-override.css --style=compressed
          sass pkg/assets/sass/additions.scss:pkg/assets/css/additions.css --style=compressed
          sass pkg/assets/sass/fonts.scss:pkg/assets/css/fonts.css --style=compressed
      
      - name: Compile TypeScript to JavaScript
        run: |
          mkdir -p pkg/assets/js
          tsc

      - name: Convert PHP files to HTML
        run: |
          # Process main index.php
          php -f index.php > index.html
          
          # Process 404.php
          php -f 404.php > 404.html
          
          # Process all PHP files in pkg/pages directory
          for file in pkg/pages/*.php; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              name="${filename%.*}"
              echo "Processing $file to pkg/pages/${name}.html"
              php -f "$file" > "pkg/pages/${name}.html"
            fi
          done

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true

